// Generated by CoffeeScript 1.3.3
(function() {
  var Game, app, express, http, io, server;

  express = require("express");

  app = express();

  http = require('http');

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.use(express.bodyParser());
    app.use(app.router);
    app.use(express["static"]("" + __dirname + "/public"));
    app.set("views", "" + __dirname + "/views");
    return app.set("view engine", "jade");
  });

  app.get("/", function(req, res) {
    return res.render("index");
  });

  app.get("/camera", function(req, res) {
    return res.render("camera");
  });

  app.get("/game", function(req, res) {
    return res.render("pong");
  });

  server = http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

  Game = require('./lib/game/start');

  io = require('socket.io').listen(server, app);

  global.canvas_width = 800;

  global.canvas_height = 600;

  io.sockets.on('connection', function(socket) {
    var game;
    console.log('you have connected');
    game = new Game(socket);
    socket.on('paddle_hit', function() {
      return console.log('ball hit by paddle');
    });
    return socket.on('mouse_pos', function(x) {
      game.updatePaddle(1, x);
      return game.updatePaddle(2, x);
    });
  });

}).call(this);
